<?php

namespace ContainerC5qxYfL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WQWDzztService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WQWDzzt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WQWDzzt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sport' => ['privates', '.errored..service_locator.WQWDzzt.App\\Entity\\Sport', NULL, 'Cannot autowire service ".service_locator.WQWDzzt": it references class "App\\Entity\\Sport" but no such service exists.'],
            'sportRepository' => ['privates', 'App\\Repository\\SportRepository', 'getSportRepositoryService', true],
        ], [
            'sport' => 'App\\Entity\\Sport',
            'sportRepository' => 'App\\Repository\\SportRepository',
        ]);
    }
}
