<?php

namespace ContainerC5qxYfL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZBcW8zHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZBcW8zH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZBcW8zH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AthleteController::delete' => ['privates', '.service_locator.B2JC1HM', 'get_ServiceLocator_B2JC1HMService', true],
            'App\\Controller\\AthleteController::edit' => ['privates', '.service_locator.B2JC1HM', 'get_ServiceLocator_B2JC1HMService', true],
            'App\\Controller\\AthleteController::index' => ['privates', '.service_locator.kpvCfyB', 'get_ServiceLocator_KpvCfyBService', true],
            'App\\Controller\\AthleteController::new' => ['privates', '.service_locator.kpvCfyB', 'get_ServiceLocator_KpvCfyBService', true],
            'App\\Controller\\AthleteController::show' => ['privates', '.service_locator.q9gMP9.', 'get_ServiceLocator_Q9gMP9_Service', true],
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.bw8tvv2', 'get_ServiceLocator_Bw8tvv2Service', true],
            'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator.bw8tvv2', 'get_ServiceLocator_Bw8tvv2Service', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.RdVbGrJ', 'get_ServiceLocator_RdVbGrJService', true],
            'App\\Controller\\CategoryController::new' => ['privates', '.service_locator.RdVbGrJ', 'get_ServiceLocator_RdVbGrJService', true],
            'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.W5pOP8q', 'get_ServiceLocator_W5pOP8qService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.qV1Yx19', 'get_ServiceLocator_QV1Yx19Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\SportController::delete' => ['privates', '.service_locator.WQWDzzt', 'get_ServiceLocator_WQWDzztService', true],
            'App\\Controller\\SportController::edit' => ['privates', '.service_locator.WQWDzzt', 'get_ServiceLocator_WQWDzztService', true],
            'App\\Controller\\SportController::index' => ['privates', '.service_locator.Sj6AyRR', 'get_ServiceLocator_Sj6AyRRService', true],
            'App\\Controller\\SportController::new' => ['privates', '.service_locator.Sj6AyRR', 'get_ServiceLocator_Sj6AyRRService', true],
            'App\\Controller\\SportController::show' => ['privates', '.service_locator.1axes0a', 'get_ServiceLocator_1axes0aService', true],
            'App\\Controller\\ViewSportsController::index' => ['privates', '.service_locator.Sj6AyRR', 'get_ServiceLocator_Sj6AyRRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\AthleteController:delete' => ['privates', '.service_locator.B2JC1HM', 'get_ServiceLocator_B2JC1HMService', true],
            'App\\Controller\\AthleteController:edit' => ['privates', '.service_locator.B2JC1HM', 'get_ServiceLocator_B2JC1HMService', true],
            'App\\Controller\\AthleteController:index' => ['privates', '.service_locator.kpvCfyB', 'get_ServiceLocator_KpvCfyBService', true],
            'App\\Controller\\AthleteController:new' => ['privates', '.service_locator.kpvCfyB', 'get_ServiceLocator_KpvCfyBService', true],
            'App\\Controller\\AthleteController:show' => ['privates', '.service_locator.q9gMP9.', 'get_ServiceLocator_Q9gMP9_Service', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.bw8tvv2', 'get_ServiceLocator_Bw8tvv2Service', true],
            'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator.bw8tvv2', 'get_ServiceLocator_Bw8tvv2Service', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.RdVbGrJ', 'get_ServiceLocator_RdVbGrJService', true],
            'App\\Controller\\CategoryController:new' => ['privates', '.service_locator.RdVbGrJ', 'get_ServiceLocator_RdVbGrJService', true],
            'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.W5pOP8q', 'get_ServiceLocator_W5pOP8qService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.qV1Yx19', 'get_ServiceLocator_QV1Yx19Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\SportController:delete' => ['privates', '.service_locator.WQWDzzt', 'get_ServiceLocator_WQWDzztService', true],
            'App\\Controller\\SportController:edit' => ['privates', '.service_locator.WQWDzzt', 'get_ServiceLocator_WQWDzztService', true],
            'App\\Controller\\SportController:index' => ['privates', '.service_locator.Sj6AyRR', 'get_ServiceLocator_Sj6AyRRService', true],
            'App\\Controller\\SportController:new' => ['privates', '.service_locator.Sj6AyRR', 'get_ServiceLocator_Sj6AyRRService', true],
            'App\\Controller\\SportController:show' => ['privates', '.service_locator.1axes0a', 'get_ServiceLocator_1axes0aService', true],
            'App\\Controller\\ViewSportsController:index' => ['privates', '.service_locator.Sj6AyRR', 'get_ServiceLocator_Sj6AyRRService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\AthleteController::delete' => '?',
            'App\\Controller\\AthleteController::edit' => '?',
            'App\\Controller\\AthleteController::index' => '?',
            'App\\Controller\\AthleteController::new' => '?',
            'App\\Controller\\AthleteController::show' => '?',
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\CategoryController::edit' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::new' => '?',
            'App\\Controller\\CategoryController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SportController::delete' => '?',
            'App\\Controller\\SportController::edit' => '?',
            'App\\Controller\\SportController::index' => '?',
            'App\\Controller\\SportController::new' => '?',
            'App\\Controller\\SportController::show' => '?',
            'App\\Controller\\ViewSportsController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AthleteController:delete' => '?',
            'App\\Controller\\AthleteController:edit' => '?',
            'App\\Controller\\AthleteController:index' => '?',
            'App\\Controller\\AthleteController:new' => '?',
            'App\\Controller\\AthleteController:show' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\CategoryController:edit' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:new' => '?',
            'App\\Controller\\CategoryController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SportController:delete' => '?',
            'App\\Controller\\SportController:edit' => '?',
            'App\\Controller\\SportController:index' => '?',
            'App\\Controller\\SportController:new' => '?',
            'App\\Controller\\SportController:show' => '?',
            'App\\Controller\\ViewSportsController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
