<?php

namespace ContainerC5qxYfL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1axes0aService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1axes0a' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1axes0a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sport' => ['privates', '.errored..service_locator.1axes0a.App\\Entity\\Sport', NULL, 'Cannot autowire service ".service_locator.1axes0a": it references class "App\\Entity\\Sport" but no such service exists.'],
        ], [
            'sport' => 'App\\Entity\\Sport',
        ]);
    }
}
